// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type AssetStatus = 'Available' | 'InUse' | 'Maintenance' | 'Retired';

export type AssetSummaryDto = {
    id: string;
    tag: string;
    name: string;
    status: AssetStatus;
    currentHolder: null | string;
    createdAt: string;
};

export type CreateAssetRequest = {
    tag: string;
    name: string;
};

export type HttpValidationProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
    errors?: {
        [key: string]: Array<string>;
    };
};

export type ProblemDetails = {
    type?: null | string;
    title?: null | string;
    status?: null | number | string;
    detail?: null | string;
    instance?: null | string;
};

export type ListAssetsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/assets';
};

export type ListAssetsResponses = {
    /**
     * OK
     */
    200: Array<AssetSummaryDto>;
};

export type ListAssetsResponse = ListAssetsResponses[keyof ListAssetsResponses];

export type CreateAssetData = {
    body: CreateAssetRequest;
    path?: never;
    query?: never;
    url: '/assets';
};

export type CreateAssetErrors = {
    /**
     * Bad Request
     */
    400: HttpValidationProblemDetails;
    /**
     * Conflict
     */
    409: ProblemDetails;
};

export type CreateAssetError = CreateAssetErrors[keyof CreateAssetErrors];

export type CreateAssetResponses = {
    /**
     * Created
     */
    201: AssetSummaryDto;
};

export type CreateAssetResponse = CreateAssetResponses[keyof CreateAssetResponses];
