<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="ErrorOr" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Mediator.Abstractions" />
    <PackageReference Include="Mediator.SourceGenerator">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AssetOps.Domain\AssetOps.Domain.csproj" />
  </ItemGroup>
</Project>
